# query_engine/fallback.py
# ------------------------------------------------------------------
# Layer 8b: Generate Hive SQL via a local Ollama model when the rule
#           engine fails. Sends schema + relationships as context to
#           the LLM so it only uses tables/columns we actually have.
# ------------------------------------------------------------------

import re
import requests

from config.db import fetch_all
from config.config import OLLAMA_HOST, OLLAMA_MODEL, HIVE_DATABASE


def _schema_text():
    """Build a compact schema description to ground the model.

    Reads every column from schema_context and groups them by table, so
    the LLM sees one line per table like:
        - sales(customer_id int, sales_amount double)
    """
    rows = fetch_all("SELECT table_name, column_name, data_type FROM schema_context")

    # group the columns under their table name
    schema = {}
    for table, column, data_type in rows:
        schema.setdefault(table, []).append(f"{column} {data_type}")

    lines = [f"- {table}({', '.join(columns)})" for table, columns in schema.items()]
    return "\n".join(lines)


def _relationship_text():
    """Describe the table join keys for the model, or 'None' if we have none.

    Turns each relationship row into a readable join hint like:
        - customers.customer_id = orders.customer_id
    """
    rows = fetch_all(
        "SELECT parent_table, child_table, join_key FROM relationship_context"
    )
    if not rows:
        return "None"
    return "\n".join(f"- {parent}.{key} = {child}.{key}" for parent, child, key in rows)


def _clean_sql(text):
    """Strip markdown fences and keep only the SQL statement.

    The LLM often wraps its answer in ```sql ... ``` fences and adds extra
    words. We remove the fences, then pull out the first SELECT statement
    (up to a semicolon or the end of the text).
    """
    text = re.sub(r"```sql|```", "", text)
    match = re.search(r"(SELECT[\s\S]+?)(;|$)", text, re.IGNORECASE)
    return match.group(1).strip() if match else text.strip()


def _build_prompt(query):
    """Assemble the full prompt (schema + relationships + rules + question)."""
    return f"""You are a Hive SQL expert. Convert the question into a single valid Hive SQL query.

Database: {HIVE_DATABASE}
Tables and columns:
{_schema_text()}

Relationships:
{_relationship_text()}

Rules:
- Use only the tables and columns listed above.
- Always prefix tables with the database name: {HIVE_DATABASE}.table_name
- Return ONLY the SQL query, no explanation.

Question: {query}
SQL:"""


def generate_sql_ollama(query):
    """Return Hive SQL generated by the local LLM, or None on failure.

    Steps: build the grounded prompt, call the Ollama HTTP API, clean the
    reply, and only accept it if it actually looks like a SELECT query.
    Any error (server down, timeout, bad reply) is caught and returns None
    so the caller can fall back gracefully.
    """
    prompt = _build_prompt(query)

    try:
        response = requests.post(
            f"{OLLAMA_HOST}/api/generate",
            json={"model": OLLAMA_MODEL, "prompt": prompt, "stream": False},
            timeout=120,
        )
        response.raise_for_status()

        raw_reply = response.json().get("response", "")
        sql = _clean_sql(raw_reply)
        return sql if sql.upper().startswith("SELECT") else None
    except Exception as error:
        print(f"[Ollama fallback error] {error}")
        return None


if __name__ == "__main__":
    for question in ["average order value per customer",
                     "which city has the most orders"]:
        print(f"\nQ: {question}\n  SQL: {generate_sql_ollama(question)}")
